# 資料載入

In [ ]:
import pandas as pd

with open("name_gender.txt","r", encoding="utf-8") as f:
    r = f.read()

data = r.replace("\ufeff","").split("\n")
names = [(d.split(",")[0],d.split(",")[1]) for d in data if len(d)>0]

# total 5179

In [106]:
len(names)

5179

# 名字分出來(姓氏不影響性別所以踢出)

In [ ]:
name_list = []
for name in names:
    if len(name[0]) == 2:
        name_list.append(name[0][-1])
    else:
        name_list.append(" ".join([name[0][-2], name[0][-1]]))


# 把名字轉換成向量

In [108]:
from sklearn.feature_extraction.text  import  CountVectorizer  
from sklearn.model_selection import train_test_split
import numpy as np

### X資料(first name)
vectorizer = CountVectorizer(min_df=1, token_pattern='(?u)\\b\\w+\\b')  
X = vectorizer.fit_transform(name_list)
X = X.toarray()

### y資料(gender)
y=[gender[1] for gender in names]
y=np.array(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)


In [109]:
from sklearn.naive_bayes import BernoulliNB
clf1 = BernoulliNB().fit(X_train,y_train)

In [111]:
prediction = clf1.predict(X_train)
print(prediction)
print(y_train)


['1' '1' '1' ..., '1' '1' '0']
['1' '1' '1' ..., '1' '0' '0']


In [112]:
from sklearn.metrics import accuracy_score

print('train_Accuracy: %.2f' % accuracy_score(prediction, y_train))

train_Accuracy: 0.91


In [113]:
prediction_test = clf1.predict(X_test)
print('test_Accuracy: %.2f' % accuracy_score(prediction_test, y_test))

test_Accuracy: 0.87


In [104]:
input_name = vectorizer.transform(['matt']).toarray()

print(clf1.predict(input_name))
print(clf1.predict_proba(input_name))

['0']
[[ 0.50904116  0.49095884]]


In [114]:
import pickle

In [115]:
with open("gender", "wb") as f:
    pickle.dump(clf1, f)

In [116]:
with open("gender", "rb") as f:
    c = pickle.load(f)

In [129]:
input_name = vectorizer.transform(['王']).toarray()
print(c.predict(input_name))
print(c.predict_proba(input_name))

['0']
[[ 0.50814948  0.49185052]]


In [121]:
with open("vectorizer", "wb") as f:
    pickle.dump(vectorizer, f)

In [123]:
with open("vectorizer", "rb") as f:
    v = pickle.load(f)

In [133]:
input_name = v.transform(['高 富']).toarray()
print(c.predict(input_name)[0])
print(c.predict_proba(input_name))

0
[[ 0.94386014  0.05613986]]
